# Generated by Django 3.0.8 on 2020-08-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.ManyToManyField(blank=True, to='pics.Category'),
        ),
    ]
