# Generated by Django 3.0.8 on 2020-08-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20200803_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='locale',
        ),
    ]
